export const VALID_DOCUMENT_TYPES = [
  'General Essay',
  'Formal Letter',
  'Thesis',
  'Blog Post',
  'Cover Letter',
  'Resume / CV',
  'Email (Professional)',
  'Email (Casual)',
  'Research Paper',
  'Literature Review',
  'Case Study',
  'Poem',
  'Short Story',
  'Novel Chapter',
  'Script / Screenplay',
  'Speech',
  'Press Release',
  'Newsletter',
  'Advertisement Copy',
  'Product Description',
  'Social Media Post',
  'Legal Document',
  'Contract',
  'Memorandum (Memo)',
  'Business Proposal',
  'Grant Proposal',
  'Technical Documentation',
  'User Manual',
  'API Documentation',
  'Journal Entry',
  'Reflection Paper',
  'White Paper',
  'News Article',
  'Op-Ed / Editorial',
  'Interview Transcript',
  'Meeting Minutes',
  'Executive Summary',
  'Lesson Plan',
  'Syllabus',
  'Letter of Recommendation',
  'Personal Statement',
  'Statement of Purpose',
  'Standard Operating Procedure (SOP)',
  'Policy Document',
  'Brochure',
  'Magazine Article',
  'Book Review',
  'Movie Review',
  'Recipe',
  'Creative Non-Fiction'
];
